import { deleteData, getData, postData, putData } from './client'
import type {
  AcademicWarning,
  AdminUser,
  Announcement,
  AnnouncementPayload,
  AttendanceRecord,
  Course,
  Dashboard,
  Enrollment,
  GradeRecord,
  Permission,
  PageResult,
  Role,
  PasswordResetPayload,
  ScheduleItem,
  SchedulePayload,
  Semester,
  StudentProfile,
  SystemConfig,
  AdminUserPayload,
  TeacherProfile,
  TeachingClass,
  Weather,
} from '../types/api'

export const campusApi = {
  dashboard: () => getData<Dashboard>('/api/dashboard/overview'),
  weather: () => getData<Weather>('/api/weather/guangzhou'),
  announcements: (category?: string) => getData<Announcement[]>('/api/announcements', category ? { category } : undefined),
  mySchedules: () => getData<ScheduleItem[]>('/api/schedules/my'),
  semesters: () => getData<PageResult<Semester>>('/api/semesters', { page: 1, size: 100 }),
  createSemester: (body: Omit<Semester, 'id'>) => postData<Semester>('/api/semesters', body),
  deleteSemester: (id: number) => deleteData<void>(`/api/semesters/${id}`),
  courses: () => getData<PageResult<Course>>('/api/courses', { page: 1, size: 100 }),
  createCourse: (body: Omit<Course, 'id'>) => postData<Course>('/api/courses', body),
  deleteCourse: (id: number) => deleteData<void>(`/api/courses/${id}`),
  teachers: () => getData<TeacherProfile[]>('/api/teachers'),
  students: () => getData<StudentProfile[]>('/api/students'),
  teachingClasses: () => getData<PageResult<TeachingClass>>('/api/teaching-classes', { page: 1, size: 100 }),
  createTeachingClass: (body: Omit<TeachingClass, 'id'>) => postData<TeachingClass>('/api/teaching-classes', body),
  deleteTeachingClass: (id: number) => deleteData<void>(`/api/teaching-classes/${id}`),
  enrollments: (teachingClassId: number) => getData<Enrollment[]>('/api/enrollments', { teachingClassId }),
  createEnrollment: (body: Omit<Enrollment, 'id'>) => postData<Enrollment>('/api/enrollments', body),
  deleteEnrollment: (id: number) => deleteData<void>(`/api/enrollments/${id}`),
  grades: (params?: { teachingClassId?: number; studentId?: number }) => getData<GradeRecord[]>('/api/grades', params),
  saveGrade: (body: Omit<GradeRecord, 'id' | 'totalScore'>) => postData<GradeRecord>('/api/grades', body),
  attendance: (params?: { teachingClassId?: number; studentId?: number }) => getData<AttendanceRecord[]>('/api/attendance', params),
  saveAttendance: (body: Omit<AttendanceRecord, 'id'>) => postData<AttendanceRecord>('/api/attendance', body),
  warnings: () => getData<AcademicWarning[]>('/api/warnings'),
  recalculateWarnings: () => postData<number>('/api/warnings/recalculate'),
  readOnly: (endpoint: string) => getData<unknown>(endpoint, endpoint.includes('courses') ? { page: 1, size: 100 } : undefined),
  adminAnnouncements: () => getData<Announcement[]>('/api/admin/announcements'),
  createAnnouncement: (body: AnnouncementPayload) => postData<Announcement>('/api/admin/announcements', body),
  updateAnnouncement: (id: number, body: AnnouncementPayload) => putData<Announcement>(`/api/admin/announcements/${id}`, body),
  deleteAnnouncement: (id: number) => deleteData<void>(`/api/admin/announcements/${id}`),
  adminSchedules: () => getData<ScheduleItem[]>('/api/admin/schedules'),
  createSchedule: (body: SchedulePayload) => postData<unknown>('/api/admin/schedules', body),
  updateSchedule: (id: number, body: SchedulePayload) => putData<unknown>(`/api/admin/schedules/${id}`, body),
  deleteSchedule: (id: number) => deleteData<void>(`/api/admin/schedules/${id}`),
  adminUsers: () => getData<AdminUser[]>('/api/admin/users'),
  createUser: (body: AdminUserPayload) => postData<unknown>('/api/admin/users', body),
  updateUser: (id: number, body: AdminUserPayload) => putData<unknown>(`/api/admin/users/${id}`, body),
  setUserStatus: (id: number, status: number) => putData<void>(`/api/admin/users/${id}/status/${status}`),
  resetPassword: (id: number, body: PasswordResetPayload) => putData<void>(`/api/admin/users/${id}/password`, body),
  adminRoles: () => getData<Role[]>('/api/admin/roles'),
  createRole: (body: Omit<Role, 'id'>) => postData<Role>('/api/admin/roles', body),
  updateRole: (id: number, body: Omit<Role, 'id'>) => putData<Role>(`/api/admin/roles/${id}`, body),
  adminPermissions: () => getData<Permission[]>('/api/admin/permissions'),
  createPermission: (body: Omit<Permission, 'id'>) => postData<Permission>('/api/admin/permissions', body),
  updatePermission: (id: number, body: Omit<Permission, 'id'>) => putData<Permission>(`/api/admin/permissions/${id}`, body),
  adminConfigs: () => getData<SystemConfig[]>('/api/admin/configs'),
  updateConfig: (id: number, body: Pick<SystemConfig, 'configName' | 'configValue' | 'description'>) => putData<SystemConfig>(`/api/admin/configs/${id}`, body),
}
