import { deleteData, downloadBlob, getData, postData, postFormData, putData, type DownloadProgressHandler } from './client'
import type {
  AcademicWarning,
  AdminUser,
  Announcement,
  AnnouncementPayload,
  AttendancePayload,
  AttendanceRecord,
  Course,
  CoursePayload,
  Dashboard,
  Enrollment,
  GradePayload,
  GradeRecord,
  Permission,
  PageResult,
  Role,
  PasswordResetPayload,
  ScheduleItem,
  SchedulePayload,
  Semester,
  StudentProfile,
  SystemConfig,
  AdminUserPayload,
  AdminStats,
  AcademicCalendar,
  College,
  TeacherProfile,
  TeachingClass,
  TeachingClassPayload,
  ImportResult,
  ProfileSecurity,
  Weather,
} from '../types/api'

export const campusApi = {
  dashboard: () => getData<Dashboard>('/api/dashboard/overview'),
  weather: () => getData<Weather>('/api/weather/guangzhou'),
  calendar: (params: { academicYear: string; term: number }) => getData<AcademicCalendar>('/api/calendar', params),
  calendarOptions: () => getData<AcademicCalendar[]>('/api/calendar-options'),
  announcements: (category?: string) => getData<Announcement[]>('/api/announcements', category ? { category } : undefined),
  mySchedules: () => getData<ScheduleItem[]>('/api/schedules/my'),
  classSchedules: () => getData<ScheduleItem[]>('/api/schedules/class'),
  semesters: (params?: { page?: number; size?: number; keyword?: string }) => getData<PageResult<Semester>>('/api/semesters', { page: 1, size: 100, ...params }),
  createSemester: (body: Omit<Semester, 'id'>) => postData<Semester>('/api/semesters', body),
  updateSemester: (id: number, body: Omit<Semester, 'id'>) => putData<Semester>(`/api/semesters/${id}`, body),
  deleteSemester: (id: number) => deleteData<void>(`/api/semesters/${id}`),
  courses: (params?: { page?: number; size?: number; keyword?: string }) => getData<PageResult<Course>>('/api/courses', { page: 1, size: 100, ...params }),
  createCourse: (body: CoursePayload) => postData<Course>('/api/courses', body),
  updateCourse: (id: number, body: CoursePayload) => putData<Course>(`/api/courses/${id}`, body),
  deleteCourse: (id: number) => deleteData<void>(`/api/courses/${id}`),
  colleges: () => getData<College[]>('/api/colleges'),
  teachers: () => getData<TeacherProfile[]>('/api/teachers'),
  students: () => getData<StudentProfile[]>('/api/students'),
  teachingClasses: (params?: { page?: number; size?: number; keyword?: string; academicYear?: string; term?: number }) => getData<PageResult<TeachingClass>>('/api/teaching-classes', { page: 1, size: 100, ...params }),
  createTeachingClass: (body: TeachingClassPayload) => postData<TeachingClass>('/api/teaching-classes', body),
  updateTeachingClass: (id: number, body: TeachingClassPayload) => putData<TeachingClass>(`/api/teaching-classes/${id}`, body),
  deleteTeachingClass: (id: number) => deleteData<void>(`/api/teaching-classes/${id}`),
  enrollments: (teachingClassId: number) => getData<Enrollment[]>('/api/enrollments', { teachingClassId }),
  createEnrollment: (body: { teachingClassId: number; studentId: number }) => postData<Enrollment>('/api/enrollments', body),
  deleteEnrollment: (id: number) => deleteData<void>(`/api/enrollments/${id}`),
  grades: (params?: { page?: number; size?: number; teachingClassId?: number; studentId?: number; keyword?: string; academicYear?: string; term?: number }) => getData<PageResult<GradeRecord>>('/api/grades', params),
  saveGrade: (body: GradePayload) => postData<GradeRecord>('/api/grades', body),
  updateGrade: (id: number, body: GradePayload) => putData<GradeRecord>(`/api/grades/${id}`, body),
  deleteGrade: (id: number) => deleteData<void>(`/api/grades/${id}`),
  deleteGrades: (ids: number[]) => postData<void>('/api/grades/batch-delete', ids),
  gradeTemplate: (onProgress?: DownloadProgressHandler) => downloadBlob('/api/grades/template-xlsx', onProgress),
  exportGrades: (onProgress?: DownloadProgressHandler) => downloadBlob('/api/grades/export-xlsx', onProgress),
  importGrades: (file: File) => {
    const body = new FormData()
    body.append('file', file)
    return postFormData<ImportResult>('/api/grades/import-xlsx', body)
  },
  attendance: (params?: { page?: number; size?: number; teachingClassId?: number; studentId?: number; keyword?: string; academicYear?: string; term?: number }) => getData<PageResult<AttendanceRecord>>('/api/attendance', params),
  saveAttendance: (body: AttendancePayload) => postData<AttendanceRecord>('/api/attendance', body),
  updateAttendance: (id: number, body: AttendancePayload) => putData<AttendanceRecord>(`/api/attendance/${id}`, body),
  deleteAttendance: (id: number) => deleteData<void>(`/api/attendance/${id}`),
  deleteAttendanceBatch: (ids: number[]) => postData<void>('/api/attendance/batch-delete', ids),
  attendanceTemplate: (onProgress?: DownloadProgressHandler) => downloadBlob('/api/attendance/template-xlsx', onProgress),
  exportAttendance: (onProgress?: DownloadProgressHandler) => downloadBlob('/api/attendance/export-xlsx', onProgress),
  importAttendance: (file: File) => {
    const body = new FormData()
    body.append('file', file)
    return postFormData<ImportResult>('/api/attendance/import-xlsx', body)
  },
  warnings: () => getData<AcademicWarning[]>('/api/warnings'),
  recalculateWarnings: () => postData<number>('/api/warnings/recalculate'),
  readOnly: (endpoint: string, params?: Record<string, unknown>) => getData<unknown>(endpoint, params),
  adminAnnouncements: () => getData<Announcement[]>('/api/admin/announcements'),
  adminStats: () => getData<AdminStats>('/api/admin/stats'),
  createAnnouncement: (body: AnnouncementPayload) => postData<Announcement>('/api/admin/announcements', body),
  updateAnnouncement: (id: number, body: AnnouncementPayload) => putData<Announcement>(`/api/admin/announcements/${id}`, body),
  deleteAnnouncement: (id: number) => deleteData<void>(`/api/admin/announcements/${id}`),
  adminSchedules: () => getData<ScheduleItem[]>('/api/admin/schedules'),
  createSchedule: (body: SchedulePayload) => postData<unknown>('/api/admin/schedules', body),
  updateSchedule: (id: number, body: SchedulePayload) => putData<unknown>(`/api/admin/schedules/${id}`, body),
  deleteSchedule: (id: number) => deleteData<void>(`/api/admin/schedules/${id}`),
  adminUsers: () => getData<AdminUser[]>('/api/admin/users'),
  createUser: (body: AdminUserPayload) => postData<unknown>('/api/admin/users', body),
  updateUser: (id: number, body: AdminUserPayload) => putData<unknown>(`/api/admin/users/${id}`, body),
  setUserStatus: (id: number, status: number) => putData<void>(`/api/admin/users/${id}/status/${status}`),
  resetPassword: (id: number, body: PasswordResetPayload) => putData<void>(`/api/admin/users/${id}/password`, body),
  adminRoles: () => getData<Role[]>('/api/admin/roles'),
  createRole: (body: Omit<Role, 'id'>) => postData<Role>('/api/admin/roles', body),
  updateRole: (id: number, body: Omit<Role, 'id'>) => putData<Role>(`/api/admin/roles/${id}`, body),
  adminPermissions: () => getData<Permission[]>('/api/admin/permissions'),
  createPermission: (body: Omit<Permission, 'id'>) => postData<Permission>('/api/admin/permissions', body),
  updatePermission: (id: number, body: Omit<Permission, 'id'>) => putData<Permission>(`/api/admin/permissions/${id}`, body),
  adminConfigs: () => getData<SystemConfig[]>('/api/admin/configs'),
  updateConfig: (id: number, body: Pick<SystemConfig, 'configName' | 'configValue' | 'description'>) => putData<SystemConfig>(`/api/admin/configs/${id}`, body),
  profileSecurity: () => getData<ProfileSecurity>('/api/profile/security'),
  changePassword: (body: { oldPassword: string; newPassword: string }) => putData<void>('/api/profile/password', body),
  bindEmail: (body: { email: string }) => putData<ProfileSecurity>('/api/profile/email', body),
  bindWechat: (body: { bound: boolean }) => putData<ProfileSecurity>('/api/profile/wechat', body),
}
