import { deleteData, getData, postData } from './client'
import type {
  AcademicWarning,
  AttendanceRecord,
  Course,
  Dashboard,
  Enrollment,
  GradeRecord,
  PageResult,
  Semester,
  StudentProfile,
  TeacherProfile,
  TeachingClass,
} from '../types/api'

export const campusApi = {
  dashboard: () => getData<Dashboard>('/api/dashboard/overview'),
  semesters: () => getData<PageResult<Semester>>('/api/semesters', { page: 1, size: 100 }),
  createSemester: (body: Omit<Semester, 'id'>) => postData<Semester>('/api/semesters', body),
  deleteSemester: (id: number) => deleteData<void>(`/api/semesters/${id}`),
  courses: () => getData<PageResult<Course>>('/api/courses', { page: 1, size: 100 }),
  createCourse: (body: Omit<Course, 'id'>) => postData<Course>('/api/courses', body),
  deleteCourse: (id: number) => deleteData<void>(`/api/courses/${id}`),
  teachers: () => getData<TeacherProfile[]>('/api/teachers'),
  students: () => getData<StudentProfile[]>('/api/students'),
  teachingClasses: () => getData<PageResult<TeachingClass>>('/api/teaching-classes', { page: 1, size: 100 }),
  createTeachingClass: (body: Omit<TeachingClass, 'id'>) => postData<TeachingClass>('/api/teaching-classes', body),
  deleteTeachingClass: (id: number) => deleteData<void>(`/api/teaching-classes/${id}`),
  enrollments: (teachingClassId: number) => getData<Enrollment[]>('/api/enrollments', { teachingClassId }),
  createEnrollment: (body: Omit<Enrollment, 'id'>) => postData<Enrollment>('/api/enrollments', body),
  deleteEnrollment: (id: number) => deleteData<void>(`/api/enrollments/${id}`),
  grades: (params?: { teachingClassId?: number; studentId?: number }) => getData<GradeRecord[]>('/api/grades', params),
  saveGrade: (body: Omit<GradeRecord, 'id' | 'totalScore'>) => postData<GradeRecord>('/api/grades', body),
  attendance: (params?: { teachingClassId?: number; studentId?: number }) => getData<AttendanceRecord[]>('/api/attendance', params),
  saveAttendance: (body: Omit<AttendanceRecord, 'id'>) => postData<AttendanceRecord>('/api/attendance', body),
  warnings: () => getData<AcademicWarning[]>('/api/warnings'),
  recalculateWarnings: () => postData<number>('/api/warnings/recalculate'),
  readOnly: (endpoint: string) => getData<unknown>(endpoint, endpoint.includes('courses') ? { page: 1, size: 100 } : undefined),
}
